#pragma once
#ifndef PLAYER_CAPABILITIES_H
#define PLAYER_CAPABILITIES_H

#define PLAYER_SUPPRESS_ATTACK (1<<0)
#define PLAYER_SUPPRESS_JUMP (1<<1)
#define PLAYER_SUPPRESS_DUCK (1<<2)
#define PLAYER_SUPPRESS_STEP_SOUND (1<<3)
#define PLAYER_SUPPRESS_MOVEMENT (1<<4)
#define PLAYER_SUPPRESS_USE (1<<5)
#define PLAYER_SUPPRESS_JUMP_DUE_TO_WEAPON (1<<6)
#define PLAYER_SUPPRESS_SAVE (1<<7)

#endif
