/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#pragma once
#ifndef TRIBOOL_H
#define TRIBOOL_H

// Based on boost::tribool
// Note: unlike boost::tribool the default value is indeterminate, not false

namespace detail
{
struct indeterminate_t {};
}

struct tribool;

typedef bool (*indeterminate_keyword_t)(tribool, detail::indeterminate_t);

constexpr inline bool indeterminate(tribool x, detail::indeterminate_t dummy = detail::indeterminate_t()) noexcept;

struct tribool
{
	constexpr tribool() noexcept : value(indeterminate_value) {}
	explicit constexpr tribool(bool initial_value) noexcept : value(initial_value? true_value : false_value) {}
	constexpr tribool(indeterminate_keyword_t) noexcept : value(indeterminate_value) {}

	constexpr explicit operator bool () const noexcept
	{
		return value == true_value;
	}

	tribool operator=(tribool b) {
		value = b.value;
		return *this;
	}
	tribool operator=(bool b) {
		value = b ? true_value : false_value;
		return *this;
	}
	tribool operator=(indeterminate_keyword_t) {
		value = indeterminate_value;
		return *this;
	}

	enum value_t { false_value, true_value, indeterminate_value } value;
};

constexpr inline bool indeterminate(tribool x, detail::indeterminate_t) noexcept
{
	return x.value == tribool::indeterminate_value;
}

constexpr inline tribool operator!(tribool x) noexcept
{
	return x.value == tribool::false_value? tribool(true): x.value == tribool::true_value? tribool(false) :tribool(indeterminate);
}

constexpr inline tribool operator&&(tribool x, tribool y) noexcept
{
	return (static_cast<bool>(!x) || static_cast<bool>(!y))
	? tribool(false)
	: ((static_cast<bool>(x) && static_cast<bool>(y)) ? tribool(true) : indeterminate)
	;
}

constexpr inline tribool operator&&(tribool x, bool y) noexcept
{ return y? x : tribool(false); }

constexpr inline tribool operator&&(bool x, tribool y) noexcept
{ return x? y : tribool(false); }

constexpr inline tribool operator&&(indeterminate_keyword_t, tribool x) noexcept
{ return !x? tribool(false) : tribool(indeterminate); }

constexpr inline tribool operator&&(tribool x, indeterminate_keyword_t) noexcept
{ return !x? tribool(false) : tribool(indeterminate); }

constexpr inline tribool operator||(tribool x, tribool y) noexcept
{
	return (static_cast<bool>(!x) && static_cast<bool>(!y))
	? tribool(false)
	: ((static_cast<bool>(x) || static_cast<bool>(y)) ? tribool(true) : tribool(indeterminate))
	;
}

constexpr inline tribool operator||(tribool x, bool y) noexcept
{ return y? tribool(true) : x; }

constexpr inline tribool operator||(bool x, tribool y) noexcept
{ return x? tribool(true) : y; }

constexpr inline tribool operator||(indeterminate_keyword_t, tribool x) noexcept
{ return x? tribool(true) : tribool(indeterminate); }

constexpr inline tribool operator||(tribool x, indeterminate_keyword_t) noexcept
{ return x? tribool(true) : tribool(indeterminate); }

constexpr inline tribool operator==(tribool x, tribool y) noexcept
{
	return (indeterminate(x) || indeterminate(y))
	? indeterminate
	: ((x && y) || (!x && !y))
	;
}

constexpr inline tribool operator==(tribool x, bool y) noexcept { return x == tribool(y); }

constexpr inline tribool operator==(bool x, tribool y) noexcept { return tribool(x) == y; }

constexpr inline tribool operator==(indeterminate_keyword_t, tribool x) noexcept
{ return tribool(indeterminate) == x; }

constexpr inline tribool operator==(tribool x, indeterminate_keyword_t) noexcept
{ return tribool(indeterminate) == x; }

constexpr inline tribool operator!=(tribool x, tribool y) noexcept
{
	return (indeterminate(x) || indeterminate(y))
	? indeterminate
	: !((x && y) || (!x && !y))
	;
}

constexpr inline tribool operator!=(tribool x, bool y) noexcept { return x != tribool(y); }

constexpr inline tribool operator!=(bool x, tribool y) noexcept { return tribool(x) != y; }

constexpr inline tribool operator!=(indeterminate_keyword_t, tribool x) noexcept
{ return tribool(indeterminate) != x; }

constexpr inline tribool operator!=(tribool x, indeterminate_keyword_t) noexcept
{ return x != tribool(indeterminate); }

#endif
